version: '3.8'

services:
  s-ui:
    image: sellength/s-ui_rebuild:latest
    container_name: s-ui
    hostname: "s-ui-docker"
    restart: unless-stopped
    tty: true
    network_mode: host
    environment:
      - SINGBOX_API=127.0.0.1:1080
      - SUI_DB_FOLDER=/usr/local/s-ui/db
      - SUI_BIN_FOLDER=/usr/local/s-ui/bin
      - TZ=Asia/Shanghai
      - enable_deprecated_special_outbounds=true
    volumes:
      - "singbox:/usr/local/s-ui/bin"
      - "./db:/usr/local/s-ui/db"
      - "./cert:/usr/local/s-ui/cert"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2095/app/login"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  sing-box:
    image: sellength/s-ui_rebuild-singbox:latest
    container_name: sing-box
    restart: unless-stopped
    network_mode: host
    volumes:
      - "singbox:/app"
      - "./cert:/cert"
    depends_on:
      s-ui:
        condition: service_healthy

volumes:
  singbox: